name: CI
on:
  push:
    branches:
      - dev
    paths:
      - 'src/main/resources/application.yaml'
jobs:
  Job1:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Archive Application Yaml
        uses: actions/upload-artifact@v3
        with:
            name: yaml
            path: src/main/resources/application.yaml
  Job2:
    name: Download yaml
    needs: Job1
    runs-on: ubuntu-latest
    steps:
      - name: Download the release artifact
        uses: actions/download-artifact@v2
        with:
          name: yaml
  Job3:
    name: Chekout to another repo with main branch
    needs: Job2
    runs-on: ubuntu-latest
    steps:
      - name: checkout Upload Artifact to if Dev exist
        uses: actions/checkout@v3
        with:
          repository: arpitk-tcs-test/gh-second
          fetch-depth: 0
          path: dev
      - name: Upload Yaml
        uses: actions/upload-artifact@v3
        with:
          name: yaml
          path: src/main/resources/application.yaml