name: CI
on:
  push:
    branches:
      - dev
    paths:
      - 'src/main/resources/application.yaml'
jobs:
  Job1:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Archive Application Yaml
        uses: actions/upload-artifact@v3
        with:
            name: yaml
            path: src/main/resources/application.yaml
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: yaml
  Job2:
    name: Upload yaml to another repo
    needs: Job1
    runs-on: ubuntu-latest
    steps:
      - name: Download the release artifact
        uses: actions/download-artifact@v2
        with:
          name: yaml